language: python
python:
- 2.7
install:
- python setup.py develop
script:
- pytest
deploy:
  provider: pypi
  user: torfeld6
  password:
    secure: zcC2VbRDfwMJFk6UZ99zHdmiywE2ge+3c9z2SPMa9nyny4At8dXjFzCFpBPf1nNUo2SPi/VPmtFDrYJxEBbbc/HjWUv6s5WsF2MQxS56P1dCSIBqHkHwoFYZhuNoNWwHBRDLmGn0Zi6LSZd9MVRRZCN3O2WIpwNiIw/vwo0wE1FBuUgViG8dRM70+UHCWXKuVaPuVc0qnd6JGA5Vk5839t7y1Vzv1vBlZG9mmXuYZbdCsMt3OU/IADtDc+z88Y27Q3P3F2U5WFKPWRqoUbQekp1Qezor4GrPVcEV52kUolloU0lngMHL7vnWpcZ77khjalJJg0FA+RpBGJTNl4zkRgP6driE+08ZvsD2lbbiLzSsTULSPbKp3Ugd2tQCecG5SCr/22mxsG4w9F7i2rB3c3KVsJzLXM0aLHT1ku8iEhM0d0K9t69e77oVP7rLU/UlTcOsdGLxy7rcfWy519FDsQFt7bD7lkFnZ29zu/Bb813cDg6QvGerlVsTpozbDEQbqUsmVLK7fVcIrPADbS/MLHb+mn9zNTMo2UI//9D+yM7meZlqi4zoiAwT0mLXIwtBDRKkEyxF1qTg5ydCeRC+PVFEZ5MtpV1u2+f082jo/oduxQRrGhc+9M0Tnzv8JTfgTbGEmK99+My2aFRvdGsAomDsKVcBaC+NUVA3LDt0fqg=
