language: python
python:
- 2.7
install:
- python setup.py develop
script:
- pytest
deploy:
  provider: pypi
  user: torfeld6
  password:
    secure: XkM+MGLDh9SGEzkCZAhDhQme+8O6WSrjJDynsBERViNyYwiukK27l+4XFQxXniynr2R3FKdSCC4fc4vIh9GIeLFxZqFaXxCjkzKHIcnM9odtIkAQtsjYd9/hSHYhavNEDPqcVDAMp/GQkjyBU8ioFy1z4IgTDNKfOTtXy3+CC9GIbbzHIGforpEp/i4b8olZZ8r7/WEuqm8uDib1eXrvZBfTdTbkQ+/uemVNAT3AVOoK1Hz+xCQyRBzkBpuKNBNSP9VfM+p42k3EddLilUy7EIF1aIV6SRGEApnx2eTtnhI4VGSfl6gRom08vPD/lDiZUkPd5I3lXYo1f4EQzwlGRLVmGLKlCrBgR9Dne89z3LgbcHtY+5cg3txNN8IrBDaifOy/mw7ghhvfflT/ZA/wug2xsh7RF5/HMzURA6dF7UdoexiX51BJMteO0vIOing5dLhNwyluB4c3iJTMTSgrCayiizW5nkh2VcvuXjkzcE0LSnw5L9Sg09dfN7zc2JLf6YvEQ1IIklgcEIfaBU69G0hNoftYoqQF5tvRc5Ci7N8Gt/eNHgFcKMpxjaLsNzFZI4jvA+cVnqLNUklG/om7Ko5sYCvpr5JIW5dhNwAxjqYT2U9cA9vCQEWlEWeQQrnNl0hg0uooyOPmJNai7RY+nSaOMMNUw/syaqZj+lN+NcA=
