language: python
python:
- 2.7
install:
- python setup.py develop
script:
- pytest
deploy:
  provider: pypi
  user: torfeld6
  password:
    secure: dSEHlt7QC+oydSVXkP1u7KNQBmMf9Dn16Uc+FOCrA9YVNaWSGJ5DB++faYRmH3FOXfl4jijS4gi/rDB+J91i6lDLC5tmF44DybUw5fSxLIuJVsSQo3h+VK8Sh800JFkgs+rqsslw3j7H8+soGFZqaPPYZueQJnkja9krMwVBjdM1Fc6UZzEL8jfCy7jgkQehQkV1rF4UL1fUjQL0iAaYDuu56xLMPPkDn0oNIwMnvY+S2359CPIc808t1CfZ9e9yKF98KDUtkWuVSU0jm9giO6QiKFVW9diXwhph8IX3GDpMGoc8S3VnXf49eMy2IvWVXqJktFz6CCcF3cavQG/nyYxW1cn5HRDpDbITQtVRFGgqHWf2Ar/nkHb70fd2SoP08tOZ7ph6T5kwr6moIuuwceHkx5lrFsCsPmdYJdGuXtaqQhMa43gyCewSb1XJdmMeGaOs8UqVUWCXIOif1aM5dxrgGvFRGu23LC6Ke/TnLAQ4IqRgqiSFreDQtUZlIlVHJnJL17H1eemmerATcipDrD65OFU/89pbx8370rAcmh2L+9HuXLKjiptavzt2lpEAp2eranX/DJe6nqQXonocTrZxQ0bDSk5SQunGN4KBUgR1di/GOIRdTogWQrk3OU6X5Om7hjpAAdRAH6jqb8QxgBMFttuFz/JfvkoTL4V0ABs=
