language: python
python:
- 2.7
install:
- python setup.py develop
script:
- pytest
deploy:
  provider: pypi
  user: torfeld6
  password:
    secure: PpoS+gHjVEVVf3DGEp4NfV231efjQF4DzDMHc5eIKsBVpYP2nRlmLV+bdeae/w5lN9FfLe9oZ1QWi41t4OEDtZStvFnKtlz+Wyty7koXebmuq6K4x6b7w7Jos+IuX4OPQOZEB32tJMeg1NMthaV14cwaiOlPZ5RlaY7A4FwCy3oqItXFcQwPjTCanyOLwtVm9PN4GQwKnMzV0kvHCRFlQjJcZq5+rZ5FK2Oqgz60EcUtLTPpOtLHQ6MzsCyY32zdzbU4X+8wABFuzBIUXBGYNfoYxIX8dCDg5L7lNGMq2hwh6zDYjP46TuCQ6l5r3ui/00qMLYiX80Q+Q4R10I/q9cNFQy83EY1jlnW3rYzFxsdTQHW5EDI238GQEPVGNuHJ1oVzZ/GwUvyPWn7KhQO7vzYxrCLaRN8h8T9spHv9pgVNd5fx8zb8V1NI1ecpZgsmBQawMQaoGHG8VWgsaSQ3nL0E5BeEDfc1aEUwGKS2vPOLMRbVIkH7Fm7BQiuyUe5+pg1Nw+ikaOV7g56cjMpafL4176zHHtnKWyMBgIfDp1Nd4L9YfNOWCNBOtsRyOoPzioRobAd6Ib0fyPjiuLOwpGSKaGaQ05s3kUAhGLzH28K5f6p5YblHagJz9iUljk6ElsJTZ7plmNrcmz8yFxyBLTWHzEbArXk+oExPsY0hd5g=
