language: python
python:
- 2.7
install:
- python setup.py develop
script:
- pytest
deploy:
  provider: pypi
  user: torfeld6
  password:
    secure: Bf0Fyp3ZBiLW28masAHYSbgWVEcKxce81SMbqUmMMRO62mVuqJ0cS7TrNBUXeG+roTpb9c14cf3PoGjUAKefdGRTmnscjg4OKR1RsylUI2nUmNboc7mL6qIuKxJdhx0sQEMjkhBOQFwo9oj4OPk/y7RIZEY5z2XNEs95cyUUjTUd0VOMcTgnO9PslCBOQWSpYF9aDb6X9XGBKieBeRSTxunPUbab8r4DXcF1yL7jCIL/SvqLIz7bXJq2gtm3utbkn0fvF4HYT2U0fNTGJPi2bzzqZPDF4w0Ei+mc+xVmW1lORE44gTJ9Rh/m2G4TPI9jUqO+s7x3KktPjhB/XqTqo7mGcE4y12ZbYxp0uaHER/uC0xVbnOQ9eGLTvhE8m/omCT7UyDNqqN6Zmz35I0vDfeFsBOZDlB6rcQs2PIxtTVw22t+hP5T+dZhK4FjWkzn1GdIzz4vCyTKgPExAa2Ua4BzX2UIeRdCZLfffeWORw3vvWmLWz5+FkGK2zBzDCs5dBpcxJNziOZaYJ9Ippj46AYvjHJfHQXb2XzU0DEE7/TwMmd/A4p175MEUSmc1nCaX3JnYL5DUg0m33nj83HkRc7EA4Cvrv7IOJD+F9pfss52YiWX/je6G7xjRX251pcqhy8yoU+RdXeD4kOMQ7mXdm4IvJ9L34KPVMg8EzKkSwB8=
