# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version:
          [
            "3.2.x",
            "3.3.x",
            "3.4.x",
            "3.5.x",
            "3.6.x",
            "3.7.x",
            "3.8.x",
            "3.9.x",
          ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install coveralls pytest-cov
          python setup.py develop
      - name: Test with pytest
        run: |
          pytest --cov=kudu
          coveralls
        env:
          KUDU_USERNAME: ${{ secrets.KUDU_USERNAME }}
          KUDU_PASSWORD: ${{ secrets.KUDU_PASSWORD }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
