# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test Python Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install coveralls pytest-cov
          python setup.py develop
      - name: Test with pytest
        run: |
          pytest --cov=kudu
          coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GH_TOKEN }}
          KUDU_USERNAME: ${{ secrets.KUDU_USERNAME }}
          KUDU_PASSWORD: ${{ secrets.KUDU_PASSWORD }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
